name: Deploy Application to ECS

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - 'microservice/**'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  SonarScan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    env:
      SONAR_PROJECT_KEY: "FIAP-11soat-grupo-21_api-microservice-kitchen-order"
      SONAR_ORGANIZATION: "fiap-11soat-grupo-21"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Clean workspace
        run: |
          rm -rf .scannerwork || true
          go clean -testcache

      - name: Run tests with coverage
        run: |
          go test ./... -coverprofile=coverage.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.verbose=true
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.coverage.exclusions="**/*_test.go,**/*mock*.go,**/mocks/**,**/bdd/**"
  build:
    needs: [SonarScan]
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}
    env:
      REGISTRY: ghcr.io
      TOKEN: ${{ secrets.GHCR_TOKEN }}
      USERNAME: ${{ github.actor }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase IMAGE_NAME
        id: set-image-name
        run: |
          image_name="${GITHUB_REPOSITORY,,}"
          echo "image_name=${image_name}" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${image_name}" >> $GITHUB_ENV

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.set-image-name.outputs.image_name }}
          tags: |
             type=schedule
             type=ref,event=branch
             type=ref,event=pr
             type=semver,pattern={{version}}
             type=semver,pattern={{major}}.{{minor}}
             type=semver,pattern={{major}}
             type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./microservice/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set image output
        id: set-image
        run: |
          image_tag="sha-${GITHUB_SHA:0:7}"
          echo "IMAGE_TAG=${image_tag}" >> $GITHUB_ENV
          echo "image=${REGISTRY}/${IMAGE_NAME}:${image_tag}" >> $GITHUB_OUTPUT

  terraform-apply:
    needs: build
    name: Deploy - Terraform Apply
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      GIT_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      IMAGE: ${{ needs.build.outputs.image }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # Update Terraform to a version that supports check blocks referencing variables
          terraform_version: "1.6.6"

      - name: Setup SSH agent for git
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.GIT_SSH_KEY }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Adjust tfvars with image tag
        working-directory: infra
        run: |
          sed -i -e "s|GHCR_IMAGE_TAG|${IMAGE}|g" values.tfvars

      - name: Terraform Init
        working-directory: infra
        run: |
          terraform init -input=false

      - name: Terraform Apply
        working-directory: infra
        run: |
          terraform plan -input=false -var-file=values.tfvars
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "This is a workflow_dispatch event. Performing a terraform plan first."
            terraform apply -input=false -var-file=values.tfvars -auto-approve
          else
            terraform apply -input=false -var-file=values.tfvars -auto-approve -target=module.ecs_service
          fi
          

      - name: Done
        run: echo "Terraform apply finished."
